# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/df0bede7-4b2f-4864-9b43-f5364bab0833";
    fsType = "btrfs";
    options = [
      "subvol=@nixos"
      "compress=zstd"
    ];
  };

  fileSystems."/mnt/btrfs" = {
    device = "/dev/disk/by-uuid/df0bede7-4b2f-4864-9b43-f5364bab0833";
    fsType = "btrfs";
    options = [ "subvol=/" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F5B5-5C61";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/041d0523-acfc-4b73-894b-5daafe63477d";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/44d1bb48-784b-47f7-b6d4-40bfa93b9356"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
